### ISSUE TITLE
global scope of KDE e.V.

### ISSUE THREAD

**Issue by lydiapintscher** [SOM-Research/OSSFoundations#1]
KDE e.V. is marked as not having global scope. We do however support contributors from all over the world and our software is used all around the world.

**Comment by jlcanovas** [comment]
Hi @lydiapintscher! thanks for your contribution. 

I've been checking that foundation and I agree with you, the foundation does have an international scope. I bet we saw that it was a german-based foundation and desk-rejected it without further analysis. I'll update the list asap!

**Comment by lydiapintscher** [comment]
Thank you! :)
