### ISSUE TITLE
2 more organizations

### ISSUE THREAD

**Issue by LawrenceHecht** [SOM-Research/OSSFoundations#13]
https://ethereum.foundation/
https://www.oasis-open.org/

**Comment by jlcanovas** [comment]
Noted! thanks Lawrences! We'll update the dataset ASAP :)

**Comment by jlcanovas** [comment]
thanks @LawrenceHecht for the reminder, the developer in charge of the website left and I am the one now 😅

I can confirm OASIS Open is there. Only Ethereum is missing. I promise I'll add it 😄

**Comment by jlcanovas** [comment]
Added (and sorry for the almost-endless delay 😅)
