### ISSUE TITLE
Subversion Corporation is gone

### ISSUE THREAD

**Issue by ShaneCurcuru** [SOM-Research/OSSFoundations#2]
Subversion Corporation dissolved as an independent entity when it joined the Apache Software Foundation. As best I understand your criteria - current legal organizations dealing with FOSS software - this entry should be deleted from your dataset.

**Comment by jlcanovas** [comment]
Hi @ShaneCurcuru, thanks for the information, we were not aware of its dissolution when we conducted the study, I'll update the list asap

**Comment by jlcanovas** [comment]
Fixed! Thks!
