### ISSUE TITLE
Open Source Collective link is broken

### ISSUE THREAD

**Issue by kingthorin** [SOM-Research/OSSFoundations#42]
![image](https://github.com/SOM-Research/OSSFoundations/assets/7570458/4c9eead1-c3fa-4527-914c-ce3d02dddb95)

I guess since the scheme is excluded it is resolved locally:
![image](https://github.com/SOM-Research/OSSFoundations/assets/7570458/71b32ce2-3e35-4abe-a13d-a71f7f634163)

Making `https://som-research.github.io/OSSFoundations/oscollective.org` which fails.

**Comment by jlcanovas** [comment]
Hi @kingthorin,

thanks for reporting this issue, I'll fix it asap!

**Comment by jlcanovas** [comment]
Hi again, 

issue fixed, the link now targets the proper URL:

![image](https://github.com/SOM-Research/OSSFoundations/assets/1996760/dcb51843-c918-445f-908d-71e0f98d9ede)

Thanks!
