### ISSUE TITLE
Remove dead org URLs that redirect to gambling sites 

### ISSUE THREAD

**Issue by ShaneCurcuru** [SOM-Research/OSSFoundations#43]
I would recommend removing or somehow very clearly marking URLs of apparently-dead organizations that now redirect to gambling sites.  While this is not necessarily an indication the organization is dissolved, it's a good clue.  More to the point, we probably don't want to send anyone to gambling sites unexpectedly!

http://www.openmedianow.org/ currently redirects to emccan-dot-org
http://www.csol.org/ contents are now an online casino guide at same address

**Comment by jlcanovas** [comment]
Hi @ShaneCurcuru, thanks for bringing this to our attention, we'll check the links we have to avoid these situations, thanks!

**Comment by jlcanovas** [comment]
Fixed on the website, I still have to sync the web data with the repository data

**Comment by jlcanovas** [comment]
See https://github.com/SOM-Research/OSSFoundations/issues/44
