### ISSUE TITLE
Dojo Foundation merged, now JS Foundation

### ISSUE THREAD

**Issue by tbm** [SOM-Research/OSSFoundations#7]
https://en.wikipedia.org/wiki/OpenJS_Foundation

> In 2016, the Dojo Foundation merged with jQuery Foundation and subsequently rebranded itself as JS Foundation and became a Linux Foundation project

**Comment by jlcanovas** [comment]
Thanks @tbm! In these days we are working on a new version of the website and your suggestions are just in time to improve the new version 🥳

**Comment by aguscm** [comment]
Dojo Foundation has been deleted and JS Foundation has been renamed to OpenJS Foundation. Thanks for your contribution!
